<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Agile.Maui.PdfGen.Sample</RootNamespace>
		<IsPackable>false</IsPackable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\PdfGen\PdfGen.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="..\agile.png" Link="agile.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

</Project>
